# Generated by Django 4.2 on 2026-03-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_maintenance', models.CharField(max_length=100)),
                ('construction_services', models.CharField(max_length=100)),
                ('cleaning_services', models.CharField(max_length=100)),
                ('outdoor_services', models.CharField(max_length=100)),
                ('installation_services', models.CharField(max_length=100)),
                ('logistics_labor', models.CharField(max_length=100)),
                ('tailoring_crafts', models.CharField(max_length=100)),
                ('food_event_support', models.CharField(max_length=100)),
                ('personal_care', models.CharField(max_length=100)),
                ('rural_services', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('full_address', models.CharField(max_length=100)),
                ('landmark', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_register',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('worker_type', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('experience', models.PositiveIntegerField()),
                ('service_area', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'worker_register',
                'ordering': ['-created_at'],
            },
        ),
    ]
