# Generated by Django 4.2.16 on 2026-03-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('requested', 'Requested'), ('accepted', 'Accepted'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('not_available', 'Not Available'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='WorkStatus',
        ),
    ]
