# Generated by Django 4.2 on 2026-03-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_booking_status_delete_workstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_available',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('not_available', 'Not Available'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='requested', max_length=20),
        ),
    ]
