# Generated by Django 4.2 on 2026-03-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('not_available', 'Not Available'), ('confirmed', 'Confirmed'), ('started', 'Work Started'), ('in_progress', 'In Progress'), ('almost_done', 'Almost Done'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20),
        ),
    ]
