# Generated by Django 4.2 on 2026-03-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_feedback_upload_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='upload_image2',
            field=models.ImageField(blank=True, null=True, upload_to='feedback_images/'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='upload_image3',
            field=models.ImageField(blank=True, null=True, upload_to='feedback_images/'),
        ),
    ]
