# Generated by Django 4.2 on 2026-03-06 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_admin_booking_workstatus_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
