# Generated by Django 4.2 on 2026-03-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='upload_image',
            field=models.ImageField(blank=True, null=True, upload_to='feedback_images/'),
        ),
    ]
